spring:
  application:
    name: weddy
  profiles:
    active: common
  config:
    import: optional:configserver:http://15.164.159.172:8888

management:
endpoints:
    web:
      exposure:
        include: refresh